name: 😿 Fix Policy Proposal
description: Template for Fix policy proposal
title: "[Fix Policy, name]: "
labels: ["policy", "bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this Fix Policy Proposal!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. test@test.com
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Describe the Fix Policy Proposal
      description: A clear and concise description of what the Fix policy is.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your proposal.
