name: 😿 Fix Terraform Proposal
description: Template for Fix terrafrom proposal
title: "[Fix Terraform, name]: "
labels: ["terraform", "bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this Fix Terraform Proposal!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. test@test.com
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Describe the Fix Terraform Proposal
      description: A clear and concise description of what the Fix Terraform is.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your proposal.
