name: 🙀 Report a security vulnerability
description: Template for reporting a security vulnerability
title: "[Vulnerability Name]: "
labels: ["vulnerability"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this security vulnerability!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. test@test.com
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Describe the security vulnerability
      description: A clear and concise description of what the security vulnerability is.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain this security vulnerability.
