# Copyright (c) 2023 EPAM Systems, Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


policies:
- name: ecc-openstack-020-security_group_ingress_unrestricted_1433_1434
  comment: '040042022000'
  description: |
    Security groups with unrestricted incoming traffic to MSSQL ports 1433, 1434
  resource: openstack.security-group
  filters:
    - type: list-item
      key: security_group_rules
      attrs:
        - type: value
          key: direction
          value: ingress
        - type: value
          key: (remote_ip_prefix=='0.0.0.0/0' || remote_ip_prefix=='::/0' || !remote_ip_prefix) && !remote_address_group_id && !remote_group_id
          value: true
        - or:
          - type: value
            key: (port_range_min<=`1433` && port_range_max>=`1433`)
            value: true        
          - type: value
            key: (port_range_min<=`1434` && port_range_max>=`1434`)
            value: true    