name: Changelog
on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*"
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    # if: startsWith(github.ref, 'refs/tags/v')
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout action
        run: git clone -b main "https://git:$PROJECT_TOKEN@git.epam.com/epmc-sec/cloudlab/cloud_custodian/ecc-actions.git" ecc-actions
        env:
          PROJECT_TOKEN: ${{ secrets.ECC_CHANGELOG_ACTION }}

      - name: Release action
        uses: ./ecc-actions/release-rulepack-action
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}
