name: Changelog
on:
  push:
    tags:
      - "v*.*"
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    # if: startsWith(github.ref, 'refs/tags/v')
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Checkout action
        run: git clone -b main "https://git:$PROJECT_TOKEN@git.epam.com/epmc-sec/cloudlab/cloud_custodian/ecc-actions.git" ecc-actions
        env:
          PROJECT_TOKEN: ${{ secrets.ECC_CHANGELOG_ACTION }}

      - name: Changelog
        id: changelog
        uses: ./ecc-actions/changelog-action
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}
          writeToFile: true
          includeInvalidCommits: true
          excludeTypes: ""

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changes }}
